#!/bin/sh

echo "start", $1, $2
set -e

python2 main.py clean
python2 main.py outage $1 > outage.csv
python2 main.py simulate < outage.csv > outage-result.csv
echo "outages done"

echo "---- MCS ----"

python2 main.py failure $2 < outage-result.csv > combi.csv
echo "generate done"

python2 main.py simulate < combi.csv > result.csv
echo "simulate done"

python2 main.py analyse < result.csv > analysis.csv

echo "---- N-1 ----"

python2 main.py n-x 1 < outage-result.csv > nx-combi.csv
echo "generate n-1 done"

python2 main.py simulate < nx-combi.csv > nx-result.csv
echo "simulate n-1 done"

python2 main.py analyse < nx-result.csv > nx-analysis.csv

echo "---- N-2 ----"

python2 main.py n-x 2 < outage-result.csv > nx2-combi.csv
echo "generate n-2 done"

python2 main.py simulate < nx2-combi.csv > nx2-result.csv
echo "simulate n-2 done"

python2 main.py analyse < nx2-result.csv > nx2-analysis.csv
